plugins:
  phpcodesniffer:
    enabled: true
    channel: beta
    config:
      standard: "PSR12"
  phpmd:
    enabled: true
    config:
      file_extensions:
        - php
      rulesets: "cleancode,codesize,controversial,design,naming,unusedcode,phpmd.ruleset.xml"
exclude_patterns:
  - "bin/"
  - "config/"
  - "public/"
  - "src/Kernel.php"
  - "tests/"
  - "var/"
  - "vendor/"
  - "node_modules/"
  - "*.*"
